name: Deploy HackTree Pages

on:
    pull_request:
      types:
        - closed

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Fastn
        run: sh -c "$(curl -fsSL https://fastn.io/install.sh)"

      - name: Run Node.js Script
        run: node build.js

      - name: Copy Contents to gh-pages Branch
        run: |
          mkdir deploy
          cp -R rendered/* deploy/
          cd deploy
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deployed from GitHub Actions"
          git push --force --quiet "https://${{ secrets.PERSONAL_ACCESS_TOKEN }}" master:gh-pages
