name: Deploy HackTree Pages

on:
    pull_request:
      branches: gh-pages
      types:
        - closed

jobs:
  deploy:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Fastn
        run: sh -c "$(curl -fsSL https://fastn.io/install.sh)"

      - name: Run Node.js Script
        run: node build.js
