name: Deploy HackTree Landing Page

on:
    push:
      branches: main

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Fastn
        run: sh -c "$(curl -fsSL https://fastn.io/install.sh)"

      - name: Build and Deploy
        run: |
          cd hacktree
          fastn build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.build
          keep_files: true
