name: Deploy HackTree Landing Page

on:
    push:
      branches: main

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Fastn
        run: sh -c "$(curl -fsSL https://fastn.io/install.sh)"

      - name: Build and Deploy
        run: |
          cd hacktree
          echo "Using '$CI_REPOSITORY_NAME_SLUG/' as the base while building"
          fastn build --base=/$CI_REPOSITORY_NAME/
      - name: copy CNAME if found
        run: '(test -f CNAME && cp CNAME .build) || echo "CNAME does not exist, skipping step"'
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.build
          keep_files: true
